[build]
  command = "yarn build"
  functions = "dist"
[[redirects]]
  from = "/"
  to = "/.netlify/functions/api/"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true